#!/bin/bash



# count the number of directories and sub-directories in the current directory

count=0

for item in *; do

	  if [ -d "$item" ] && [ "$item" != "." ] && [ "$item" != ".." ]; then

		      count=$((count + 1))

		          count=$((count + $(find "$item" -type d | wc -l)))

			    fi

		    done



		    # print the count

		    echo $count


